### ISSUE TITLE
Tensor flat of full connection layer input

### ISSUE THREAD

**Issue by a73013110** [seathiefwang/FaceRecognition-tensorflow#1]
小弟幾個月前也在做類似的東西, 參考作者的圖片輸入, 
發現原來之前自己對於圖片內容想法是錯的, 
經修改後, 再參考作者卷積層加入dropout的想法, 成功實現相同功能~
但小弟這邊有個問題
神經網路中：
#全連接層
Wf = weightVariable([8\*16\*32, 512])
小弟覺得是: Wf = weightVariable([8\*8\*64, 512])
雖然結果是一樣的, 但意義感覺不一樣
想問問作者您怎麼覺得是: Wf = weightVariable([8\*16\*32, 512]) 呢~

**Comment by seathiefwang** [comment]
谢谢你的提问与建议，这个地方是我的疏忽，8*8*64 才是更妥当的写法。
