### ISSUE TITLE
这个只能识别出是不是自己的脸吧?能识别出别人的脸吗?

### ISSUE THREAD

**Issue by dapsjj** [seathiefwang/FaceRecognition-tensorflow#21]
比如get_my_faces我用摄像头提取了10000张自己的照片，如果is_my_face运行时候是别人，比如是Tom的坐在电脑前，那么怎么能判断出这个人是谁?目前是不是只能判断出是不是自己，判断不了具体是谁？

**Comment by sunbaigui** [comment]
@seathiefwang can you share me your email address, I've got a JD for you to see if you're interested.

**Comment by seathiefwang** [comment]
@dapsjj 这是一个二分类的模型，只能分辨自己与其他人，这个一个用于学习的demo。

**Comment by seathiefwang** [comment]
@sunbaigui daidonggen@qq.com

**Comment by dapsjj** [comment]
@seathiefwang 好的，明白了。
