### ISSUE TITLE
python的cv2安装不上，能不能用别的框架替换一下？？

### ISSUE THREAD

**Issue by ithjz** [seathiefwang/FaceRecognition-tensorflow#4]
python的cv2安装不上，能不能用别的框架替换一下？？
E:\ProgramData\Anaconda3\python.exe "D:/360c/FaceRecognition-tensorflow-master (1)/FaceRecognition-tensorflow-master/get_my_faces.py"
RuntimeError: module compiled against API version 0xb but this version of numpy is 0xa
Traceback (most recent call last):
  File "D:/360c/FaceRecognition-tensorflow-master (1)/FaceRecognition-tensorflow-master/get_my_faces.py", line 1, in <module>
    import cv2
ImportError: numpy.core.multiarray failed to import

**Comment by seathiefwang** [comment]
可以用dlib替代一下，看这个问题是numpy的问题，试着升级一下numpy版本。
